### ISSUE TITLE
umdio logo wrong font

### ISSUE THREAD

**Issue by nickav** [StartupShell/web-2017#1]
please use [this one](https://www.dropbox.com/s/7yftqnqadqhhljx/umdio-red.svg?dl=0) instead

**Comment by nbently** [comment]
Is umdio under active development/does it still work?

**Comment by nickav** [comment]
yes

**Comment by nbently** [comment]
I'll get it updated 😉

**Comment by nbently** [comment]
Fixed in https://github.com/StartupShell/web-2017/commit/5d65789d59ec93515f0672e2e3bd62e0f24813db
