### ISSUE TITLE
Events Scraper is broken

### ISSUE THREAD

**Issue by mattjfan** [StartupShell/web-2017#7]
Site doesn't scrape events from FB, and google calendar isn't being updated

**Comment by samueldrozdov** [comment]
I'm pretty sure it works in reverse. The event scraper pulls from the Google Calendar. The Google Calendar events should have the following info:
- name, date, location
- link to event (eq. Facebook) (this should be included in the description like this `[event_link]`)
- link to cover photo (this should be included in the description like this `{img_link}`)
